---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
suites:
  - name: prokect
    run_list:
      - recipe[project::default]
    attributes:
