---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
suites:
  - name: project
    run_list:
      - recipe[project::operating_system]
      - recipe[project::nginx]
      - recipe[project::rails]
    attributes:  {
      user: "vagrant",
      home: "/home/vagrant",
      path: "/home/vagrant/app",
      ruby_version: "2.3.3",
      rails_version: "5.0.1"
    }
